myMoney=float(input("\nEnter the amount of money you have: \n= "))
applePrice=float(input("\nEnter your desired price for one apple: \n= "))
maxApple=int(myMoney/applePrice)
changeAmount=float(myMoney-maxApple*applePrice)
neededAmount=float(applePrice-myMoney)
if  maxApple > 1: print(f'\nYou can buy {maxApple} apples and your change is {changeAmount:.2f} pesos.\n')
elif maxApple == 1: print(f"\nYou can buy {maxApple} apple and your change is {changeAmount:.2f} pesos.\n")
else: print(f"\nYou cannot buy any apples. You need {neededAmount:.2f} more pesos to complete a purchase.\n")